### PR TITLE
Publish PF Docker comtainer

### PR DESCRIPTION
**Pull request by greg2010**
As discussed in #44, this PR provides a github actions pipeline to automate building and pushing docker containers to ghcr repo, as well as the required changes to support that.

In the original form building standalone docker containers wouldn't be terribly useful as there was no easy way to configure database host, redis host, etc. Therefore, changes were made to pull out the useful hardcoded options into environment variables. I tried to make sure the original docker-compose setup works with minimal changes (apart from adding the additional environment variables upon upgrade), but I don't personally use it nor am I planning to, so additional testing is welcome.

**Summary of changes**
 * Github actions to build and push 2 docker images: `pathfinder` and `pf-websocket`.
 * Added Dockerfile for `pf-websocket` (was a `compose` image with the php app mounted inside in runtime before)
 * Removed `CONTAINER_NAME` environment variable
 * Added the following variables:
   * `MYSQL_HOST`
   * `MYSQL_PORT`
   * `MYSQL_USER`
   * `MYSQL_PF_DB_NAME`
   * `MYSQL_UNIVERSE_DB_NAME`
   * `MYSQL_CCP_DB_NAME`
   * `REDIS_HOST`
   * `REDIS_PORT`
   * `PATHFINDER_SOCKET_HOST`
   * `PATHFINDER_SOCKET_PORT`
   * `SMTP_HOST`
   * `SMTP_PORT`
   * `SMTP_SCHEME`
   * `SMTP_USER`
   * `SMTP_PASS`
   * `SMTP_FROM`
   * `SMTP_ERROR`
 * Updated the relevant configs and the entrypoint to make use of the new variables

That looks like a lot of variables. However in practice for the docker-compose user the number of variables to configure hasn't changed much. Here's a difference between the `.env.example` and the actual `.env` config I tested locally:
```diff
diff .env.example .env 
1,3c1,3
< PROJECT_ROOT=""
< DOMAIN=""
< APP_PASSWORD=""
---
> PROJECT_ROOT="/home/greg2010/Documents/projects/pathfinder-containers"
> DOMAIN="localhost"
> APP_PASSWORD="12345"
7c7
< MYSQL_PASSWORD=""
---
> MYSQL_PASSWORD="redacted"
13,14c13,14
< CCP_SSO_CLIENT_ID=""
< CCP_SSO_SECRET_KEY=""
---
> CCP_SSO_CLIENT_ID="redacted"
> CCP_SSO_SECRET_KEY="redacted"
```
In other words, the setup process to run pathfinder with docker-compose hasn't gotten more complicated. 

*Note*: the images in `docker-compose.yml` are still built locally, because there are no "official" images released yet. Upon merging this PR and creating a release, docker-compose file can be updated to use the remote images instead. They should be identical to the locally built ones.

For anyone wishing to run pathfinder with a different orchestrator, there is now the option to configure all of the database hosts and much more.

**Release process**

The images are built automatically, but the releases must be triggered by hand using github releases. If anyone has an idea how to trigger github actions pipelines using released in the original pathfinder repo (if that is even desirable) please feel free to weigh in.

To trigger the job, create a tag and a github release. This will trigger the job that will result in two images (`ghcr.io/goryn-clade/pathfinder:TAG` and `ghcr.io/greg2010/pf-websocket:TAG`) to be built and pushed to ghcr repo. `latest` tag will also be updated to point to the last released image.

You shouldn't need to add any secrets or anything to the repo. These are inferred automagically. You may need to enable packages in the settings for the organization if push fails.

### CODE REVIEW

**Comment by greg2010** [comment]
cc @samoneilll

**Comment by samoneilll** [comment]
@greg2010 thank you, I'll try to find some time to look at it properly on the weekend.

**Comment by greg2010** [comment]
I'm happy to help you resolve the merge conflicts if you are still looking to get this merged. In the meantime, for anyone looking to use these images, I've published v2.2.1 in my forked repo.

**Comment by samoneilll** [comment]
Hey @greg2010 I'm sorry, I will try again to find time to deal with the merge conflicts this month.

**Comment by ZaxLofful** [comment]
Any progress on this?

**Comment by samoneilll** [comment]
Hi, 

Sorry, I've been very busy and didn't get to it. I'm waiting for a PR from Tyr for some changes he's working on that will touch the same code to avoid too many merge conflicts, and I should get to this later in Feb.

**Review by samoneilll — APPROVED** [review]

**Pull request merged**
